general:
  observed_pressure_min: 6400
  observed_pressure_max: 14000
  package_path: "~/chance_of_showers"
  date_fmt: "%Y-%m-%d"
  time_fmt: "%H:%M:%S"
  fname_datetime_fmt: "%Y-%m-%d-%H-%M-%S"
  local_timezone: "US/Eastern"
daq:
  # display options
  log_to_file: true
  display_terminal: true
  display_terminal_overwrite: true
  display_oled: true
  display_web: true
  display_web_logging_terminal: false
  verbosity: 0
  # DAQ parameters
  starting_time_minutes_mod: 1
  averaging_period_seconds: 60
  polling_period_seconds: 1
  raw_data_relative_path: "daq/raw_data"
  logs_relative_path: "daq/logs"
  log_memory_usage: true
  log_memory_usage_minutes_mod: 30
  # Web parameters
  n_last_points_web: 15
  # when the issue of drifting seconds was fixed by
  # t_start = t_start.replace(minute=t_start_minute, second=0, microsecond=0)
  end_of_drifting_seconds: "2023-05-02 01:22:08"
  # when web threading was fixed, eliminating duplicate records from multiple threads
  end_of_threading_duplicates: "2023-05-31 04:36:00"
fan_control:
  verbose: true
  fan_pin: 18
  tach_pin: 23
  wait_time: 5
  pulse: 2
  pwm_freq: 25
  min_temp: 35
  max_temp: 50
  fan_low: 30
  fan_high: 100
etl:
  saved_data_relative_path: "daq/saved_data"
# no hydra logging
# https://stackoverflow.com/a/70777327
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .
