[tool.poetry]
name = "chance-of-showers"
version = "0.0.0"
description = "DAQ and analysis code for chance_of_showers water metrics project"
authors = ["Matthew Epland"]
license = "MIT"
readme = "README.md"
packages = [{include = "chance_of_showers"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.3"
hydra-core = "^1.3.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
black = {extras = ["jupyter"], version = "^23.3.0"}
flake8 = "^6.0.0"
flake8-docstrings = "^1.7.0"
mypy = "^1.4.1"
isort = "^5.12.0"
yamllint = "^1.32.0"
powerline-status = "^2.7"
pandas-stubs = "^2.0.2.230605"
types-pillow = "^9.5.0.5"
types-pyyaml = "^6.0.12.10"
types-pygments = "^2.15.0.1"
types-colorama = "^0.4.15.11"
types-decorator = "^5.1.8.3"
types-six = "^1.16.21.8"

[tool.poetry.group.daq]
optional = true

[tool.poetry.group.daq.dependencies]
adafruit-circuitpython-mcp3xxx = "^1.4.14"
gpiozero = "^1.6.2"
rpi-gpio = "^0.7.1"
"luma.oled" = "^3.12.0"
pause = "^0.3"
polars = "^0.18.4"

[tool.poetry.group.web]
optional = true

[tool.poetry.group.web.dependencies]
flask = "^2.3.2"
flask-socketio = "^5.3.4"
simple-websocket = "^0.10.0"
python-arptable = "^0.0.2"

[tool.poetry.group.ana]
optional = true

[tool.poetry.group.ana.dependencies]
pandas = "^2.0.1"
matplotlib = "^3.7.1"
jupyterlab = "^3.6.3"
statsmodels = "^0.14.0"
jupytext = "^1.14.5"
jupyter-dash = "^0.4.2"
plotly = "^5.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py39"]
exclude = '''
/(
    \.git
  | \.venv
  | \.direnv
  | \.env
  | \.cache
  | \.github
  | __pycache__
)/
'''

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disable_error_code = [
    "import",
]
# warn_unused_ignores = true is useful when upgrading mypy versions,
# but leaving it as true all the time gives false positives when running mypy in the pre-commit env
warn_unused_ignores = false

[tool.isort]
py_version = "39"
profile = "black"
multi_line_output = 3
combine_star = "true"
group_by_package = "true"
skip_gitignore = "true"
atomic = "true"
