[tool.poetry]
name = "chance-of-showers"
version = "0.0.0"
description = "DAQ and analysis code for chance_of_showers water metrics project"
authors = ["Matthew Epland"]
license = "MIT"
readme = "README.md"
packages = [{include = "chance_of_showers"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.3"
hydra-core = "^1.3.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
black = {extras = ["jupyter"], version = "^23.3.0"}
flake8 = "^6.0.0"
yamllint = "^1.32.0"
powerline-status = "^2.7"

[tool.poetry.group.daq]
optional = true

[tool.poetry.group.daq.dependencies]
adafruit-circuitpython-mcp3xxx = "^1.4.14"
gpiozero = "^1.6.2"
rpi-gpio = "^0.7.1"
"luma.oled" = "^3.12.0"
pause = "^0.3"
polars = "^0.18.4"

[tool.poetry.group.web]
optional = true

[tool.poetry.group.web.dependencies]
flask = "^2.3.2"
flask-socketio = "^5.3.4"
simple-websocket = "^0.10.0"
python-arptable = "^0.0.2"

[tool.poetry.group.ana]
optional = true

[tool.poetry.group.ana.dependencies]
pandas = "^2.0.1"
matplotlib = "^3.7.1"
jupyterlab = "^3.6.3"
statsmodels = "^0.14.0"
jupytext = "^1.14.5"
jupyter-dash = "^0.4.2"
plotly = "^5.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py39"]
exclude = '''
/(
    \.git
  | \.venv
  | \.direnv
  | \.env
  | \.cache
  | \.github
  | __pycache__
)/
'''
