# flake8: noqa
# pylint: skip-file
# mypy: disable-error-code="name-defined"
dfp_val  # unused variable (ana/exploratory_ana.py:322)
# unreachable code after 'raise' (ana/exploratory_ana.py:370)
_.converter  # unused attribute (daq/daq.py:152)
dummy_signal  # unused variable (daq/daq.py:254)
dummy_frame  # unused variable (daq/daq.py:255)
_.when_held  # unused attribute (daq/daq.py:319)
_.when_released  # unused attribute (daq/daq.py:320)
disconnect  # unused function (daq/daq.py:499)
_.show_server_banner  # unused attribute (daq/daq.py:520)
args  # unused variable (daq/daq.py:520)
pin  # unused variable (daq/pulse_test.py:16)
_.when_held  # unused attribute (daq/switch_test.py:30)
_.when_released  # unused attribute (daq/switch_test.py:31)
pin  # unused variable (fan_control/fan_control.py:73)
dummy_signal  # unused variable (utils/bayesian_opt.py:337)
dummy_frame  # unused variable (utils/bayesian_opt.py:338)
pytorch_lightning  # unused import (utils/TSModelWrapper.py:21)
_.on_exception  # unused method (utils/TSModelWrapper.py:121)
trainer  # unused variable (utils/TSModelWrapper.py:123)
pl_module  # unused variable (utils/TSModelWrapper.py:124)
