# flake8: noqa
# pylint: skip-file
# mypy: disable-error-code="name-defined"
dfp_val  # unused variable (ana/exploratory_ana.py:348)
_.converter  # unused attribute (daq/daq.py:148)
dummy_signal  # unused variable (daq/daq.py:250)
dummy_frame  # unused variable (daq/daq.py:251)
_.when_held  # unused attribute (daq/daq.py:312)
_.when_released  # unused attribute (daq/daq.py:313)
disconnect  # unused function (daq/daq.py:492)
_.show_server_banner  # unused attribute (daq/daq.py:513)
args  # unused variable (daq/daq.py:513)
pin  # unused variable (daq/pulse_test.py:16)
_.when_held  # unused attribute (daq/switch_test.py:30)
_.when_released  # unused attribute (daq/switch_test.py:31)
pin  # unused variable (fan_control/fan_control.py:73)
dummy_signal  # unused variable (utils/bayesian_opt.py:350)
dummy_frame  # unused variable (utils/bayesian_opt.py:351)
pytorch_lightning  # unused import (utils/TSModelWrapper.py:22)
_.on_exception  # unused method (utils/TSModelWrapper.py:129)
trainer  # unused variable (utils/TSModelWrapper.py:131)
pl_module  # unused variable (utils/TSModelWrapper.py:132)
