name: black

on: pull_request  # yamllint disable-line rule:truthy

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: black
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "."
          jupyter: true
